name: ai_chat_bot
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  lottie: ^2.7.0
  flutter_animate: ^4.3.0
  http: ^1.1.2
  animated_text_kit: ^4.2.2
  #for hive database
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  #for accessing storage path
  path_provider: ^2.1.0
  get: ^4.6.6
 #for ai image generation
  dart_openai: ^5.0.0
  cached_network_image: ^3.3.1
  gallery_saver_updated: ^3.0.0
  share_plus: ^7.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
      - assets/images/
      - assets/lottie/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

